export const IPC_CHANNELS = {
  GET_NOTE: "note:get",
  GET_ALL_NOTES: "note:get-all",
  GET_COMPONENT: "plugin:get-component",
  GET_PLUGIN_HTML: "plugin:get-html",
  GET_REGISTERED_TYPES: "plugin:get-registered-types",
  IMPORT_PLUGIN: "plugin:import",
  GET_INSTALLED_PLUGINS: "plugin:get-installed",
  UNINSTALL_PLUGIN: "plugin:uninstall",
  SELECT_ZIP_FILE: "plugin:select-zip",
  EXPORT_PLUGIN_DEV: "plugin:export-dev",
  EXPORT_PLUGIN_PRODUCTION: "plugin:export-production",
  BUNDLE_PLUGIN_LOCAL: "plugin:bundle-local",
  INSTALL_PLUGIN_DEPENDENCIES: "plugin:install-dependencies",
  CLEAR_PLUGIN_DEPENDENCY_CACHE: "plugin:clear-dependency-cache",
  CLEAR_ALL_PLUGIN_DEPENDENCY_CACHES: "plugin:clear-all-dependency-caches",
  GET_PLUGIN_CACHE_STATS: "plugin:cache-stats",
  PLUGINS_CHANGED: "plugin:changed",
  PLUGIN_PROGRESS: "plugin:progress",
  GET_PLUGIN_INSTALL_PLAN: "plugin:install-plan",
  GET_PLUGIN_RESOLVED_DEPS: "plugin:resolved-deps",
  RUN_PLUGIN_CACHE_NPM: "plugin:cache-npm",
  GET_PLUGIN_LOAD_ISSUES: "plugin:load-issues",
  VALIDATE_PLUGIN_ZIP: "plugin:validate-zip",
  PLUGIN_LIST_WORKSPACE_FOLDERS: "plugin:list-workspace-folders",
  PLUGIN_LIST_SOURCE_FILES: "plugin:list-source-files",
  PLUGIN_READ_SOURCE_FILE: "plugin:read-source-file",
  PLUGIN_WRITE_SOURCE_FILE: "plugin:write-source-file",
  PLUGIN_RELOAD_REGISTRY: "plugin:reload-registry",
  PLUGIN_MKDIR_SOURCE: "plugin:mkdir-source",
  PLUGIN_CREATE_SOURCE_FILE: "plugin:create-source-file",
  PLUGIN_DELETE_SOURCE_PATH: "plugin:delete-source-path",
  PLUGIN_SELECT_IMPORT_FILES: "plugin:select-import-files",
  PLUGIN_SELECT_IMPORT_DIRECTORY: "plugin:select-import-directory",
  PLUGIN_IMPORT_FILES_INTO_WORKSPACE: "plugin:import-files-into-workspace",
  PLUGIN_IMPORT_DIRECTORY_INTO_WORKSPACE: "plugin:import-directory-into-workspace",
  NPM_REGISTRY_SEARCH: "plugin:npm-registry-search",
  PLUGIN_TYPECHECK: "plugin:typecheck",
  PLUGIN_IDE_TYPINGS: "plugin:ide-typings",
  PLUGIN_IDE_PLUGIN_TYPINGS: "plugin:ide-plugin-typings",
} as const;

export type IPCChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
