export const IPC_CHANNELS = {
  UI_GET_NATIVE_THEME_DARK: "ui:native-theme-dark",
  UI_NATIVE_THEME_CHANGED: "ui:native-theme-changed",
  UI_TOGGLE_DEVTOOLS: "ui:toggle-devtools",
  UI_QUIT_APP: "ui:quit-app",
  UI_RELOAD_WINDOW: "ui:reload-window",
  /** Open http(s) or mailto in the system browser (Electron). */
  UI_OPEN_EXTERNAL_URL: "ui:open-external-url",
  /** Main → renderer: trigger `NodexContributionRegistry.invokeCommand` (e.g. dev menu). */
  UI_RUN_CONTRIBUTION_COMMAND: "ui:run-contribution-command",
  GET_PLUGIN_RENDERER_UI_META: "plugin:get-renderer-ui-meta",
  GET_PLUGIN_MANIFEST_UI: "plugin:get-manifest-ui",
  GET_NOTE: "note:get",
  GET_ALL_NOTES: "note:get-all",
  CREATE_NOTE: "note:create",
  RENAME_NOTE: "note:rename",
  DELETE_NOTES: "note:delete-notes",
  MOVE_NOTE: "note:move",
  MOVE_NOTES_BULK: "note:move-bulk",
  PASTE_SUBTREE: "note:paste-subtree",
  SAVE_NOTE_PLUGIN_UI_STATE: "note:save-plugin-ui-state",
  SAVE_NOTE_CONTENT: "note:save-content",
  PATCH_NOTE_METADATA: "note:patch-metadata",
  GET_PLUGIN_HTML: "plugin:get-html",
  GET_REGISTERED_TYPES: "plugin:get-registered-types",
  GET_SELECTABLE_NOTE_TYPES: "plugin:get-selectable-note-types",
  IMPORT_PLUGIN: "plugin:import",
  /** Local marketplace catalog (`marketplace-index.json` under dist/plugins or NODEX_MARKETPLACE_DIR). */
  MARKETPLACE_LIST_PLUGINS: "plugin:marketplace-list",
  /** Install a `.nodexplugin` from the marketplace directory by basename (safe join). */
  MARKETPLACE_INSTALL_PLUGIN: "plugin:marketplace-install",
  GET_INSTALLED_PLUGINS: "plugin:get-installed",
  UNINSTALL_PLUGIN: "plugin:uninstall",
  SELECT_ZIP_FILE: "plugin:select-zip",
  EXPORT_PLUGIN_DEV: "plugin:export-dev",
  EXPORT_PLUGIN_PRODUCTION: "plugin:export-production",
  PUBLISH_PLUGIN_AS_FILE: "plugin:publish-as-file",
  PUBLISH_PLUGIN_TO_MARKETPLACE: "plugin:publish-to-marketplace",
  BUNDLE_PLUGIN_LOCAL: "plugin:bundle-local",
  INSTALL_PLUGIN_DEPENDENCIES: "plugin:install-dependencies",
  CLEAR_PLUGIN_DEPENDENCY_CACHE: "plugin:clear-dependency-cache",
  CLEAR_ALL_PLUGIN_DEPENDENCY_CACHES: "plugin:clear-all-dependency-caches",
  GET_PLUGIN_CACHE_STATS: "plugin:cache-stats",
  PLUGINS_CHANGED: "plugin:changed",
  PLUGIN_PROGRESS: "plugin:progress",
  GET_PLUGIN_INSTALL_PLAN: "plugin:install-plan",
  GET_PLUGIN_RESOLVED_DEPS: "plugin:resolved-deps",
  RUN_PLUGIN_CACHE_NPM: "plugin:cache-npm",
  GET_PLUGIN_LOAD_ISSUES: "plugin:load-issues",
  VALIDATE_PLUGIN_ZIP: "plugin:validate-zip",
  PLUGIN_LIST_WORKSPACE_FOLDERS: "plugin:list-workspace-folders",
  PLUGIN_LIST_SOURCE_FILES: "plugin:list-source-files",
  PLUGIN_READ_SOURCE_FILE: "plugin:read-source-file",
  PLUGIN_WRITE_SOURCE_FILE: "plugin:write-source-file",
  PLUGIN_RELOAD_REGISTRY: "plugin:reload-registry",
  PLUGIN_MKDIR_SOURCE: "plugin:mkdir-source",
  PLUGIN_CREATE_SOURCE_FILE: "plugin:create-source-file",
  PLUGIN_DELETE_SOURCE_PATH: "plugin:delete-source-path",
  PLUGIN_SELECT_IMPORT_FILES: "plugin:select-import-files",
  PLUGIN_SELECT_IMPORT_DIRECTORY: "plugin:select-import-directory",
  PLUGIN_IMPORT_FILES_INTO_WORKSPACE: "plugin:import-files-into-workspace",
  PLUGIN_IMPORT_DIRECTORY_INTO_WORKSPACE: "plugin:import-directory-into-workspace",
  PLUGIN_IMPORT_DIRECTORY_AS_NEW_WORKSPACE: "plugin:import-directory-as-new-workspace",
  NPM_REGISTRY_SEARCH: "plugin:npm-registry-search",
  PLUGIN_TYPECHECK: "plugin:typecheck",
  PLUGIN_IDE_TYPINGS: "plugin:ide-typings",
  PLUGIN_IDE_PLUGIN_TYPINGS: "plugin:ide-plugin-typings",
  PLUGIN_LOAD_NODEX_FROM_PARENT: "plugin:load-nodex-from-parent",
  PLUGIN_REMOVE_EXTERNAL_PLUGIN: "plugin:remove-external-plugin",
  PLUGIN_RENAME_SOURCE_PATH: "plugin:rename-source-path",
  PLUGIN_COPY_SOURCE_WITHIN_WORKSPACE: "plugin:copy-source-within-workspace",
  PLUGIN_COPY_SOURCE_BETWEEN_WORKSPACES: "plugin:copy-source-between-workspaces",
  PLUGIN_MOVE_SOURCE_BETWEEN_WORKSPACES: "plugin:move-source-between-workspaces",
  PLUGIN_GET_SOURCE_FILE_META: "plugin:get-source-file-meta",
  PLUGIN_OPEN_WORKSPACE_IN_EDITOR: "plugin:open-workspace-in-editor",
  PLUGIN_SCAFFOLD_PLUGIN_WORKSPACE: "plugin:scaffold-plugin-workspace",
  PLUGIN_REVEAL_WORKSPACE: "plugin:reveal-workspace",
  PLUGIN_COPY_DIST_TO_FOLDER: "plugin:copy-dist-to-folder",
  PLUGIN_GET_SOURCE_ENTRY_KIND: "plugin:get-source-entry-kind",
  PLUGIN_IDE_SET_WORKSPACE_WATCH: "plugin:ide-set-workspace-watch",
  PLUGIN_IDE_WORKSPACE_FS_CHANGED: "plugin:ide-workspace-fs-changed",
  PLUGIN_GET_USER_PLUGINS_DIR: "plugin:get-user-plugins-dir",
  PLUGIN_RESET_USER_DATA_PLUGINS: "plugin:reset-user-plugins-dir",
  PLUGIN_MAINT_DELETE_BIN_AND_CACHES: "plugin:maint:delete-bin-and-caches",
  PLUGIN_MAINT_FORMAT_NODEX: "plugin:maint:format-nodex",
  PLUGIN_MAINT_DELETE_SOURCES: "plugin:maint:delete-sources",
  /** Main-process debug log line (renderer listens; Plugin IDE panel). */
  PLUGIN_IDE_MAIN_DEBUG_LOG: "plugin:ide-main-debug-log",
  PLUGIN_IDE_GET_MAIN_DEBUG_LOGS: "plugin:ide-get-main-debug-logs",
  PLUGIN_IDE_CLEAR_MAIN_DEBUG_LOGS: "plugin:ide-clear-main-debug-logs",
  PLUGIN_GET_DISABLED_IDS: "plugin:get-disabled-ids",
  PLUGIN_SET_ENABLED: "plugin:set-enabled",
  PLUGIN_GET_INVENTORY: "plugin:get-inventory",
  /** Renderer → main: structured client log (console, debug dock, daily file). */
  NODEX_CLIENT_LOG: "nodex:client-log",
  /** Opened project folder (notes DB + assets). */
  PROJECT_GET_STATE: "project:get-state",
  PROJECT_SELECT_FOLDER: "project:select-folder",
  /** No longer creates a temp dir; returns empty workspace (WPN scratch uses IndexedDB). */
  PROJECT_START_SCRATCH_SESSION: "project:start-scratch-session",
  /** Deprecated: scratch WPN is in IndexedDB; open a folder from Notes to persist on disk. */
  PROJECT_SAVE_SCRATCH_TO_FOLDER: "project:save-scratch-to-folder",
  /** Deprecated: clear scratch data from the app (IndexedDB) instead. */
  PROJECT_NEW_SCRATCH_SESSION: "project:new-scratch-session",
  /** Renderer pulls WPN rows from an in-memory legacy temp scratch session before main clears it. */
  PROJECT_PULL_LEGACY_SCRATCH_WPN_MIGRATION: "project:pull-legacy-scratch-wpn-migration",
  /** After renderer merged into IndexedDB, main closes temp scratch and sets migration flag. */
  PROJECT_ACK_LEGACY_SCRATCH_WPN_MIGRATION: "project:ack-legacy-scratch-wpn-migration",
  PROJECT_OPEN_PATH: "project:open-path",
  PROJECT_ADD_WORKSPACE_FOLDER: "project:add-workspace-folder",
  PROJECT_REVEAL_FOLDER: "project:reveal-folder",
  PROJECT_REFRESH_WORKSPACE: "project:refresh-workspace",
  /** Remove one folder from the merged workspace; optional move to OS trash. */
  PROJECT_REMOVE_WORKSPACE_ROOT: "project:remove-workspace-root",
  /** Reorder merged sidebar projects (swap adjacent root-level blocks). */
  PROJECT_SWAP_WORKSPACE_BLOCK: "project:swap-workspace-block",
  /** Set optional display label for a workspace root (saved in project prefs). */
  PROJECT_SET_WORKSPACE_LABEL: "project:set-workspace-label",
  PROJECT_ROOT_CHANGED: "project:root-changed",
  ASSET_LIST: "asset:list",
  ASSET_LIST_BY_CATEGORY: "asset:list-by-category",
  ASSET_PICK_IMPORT: "asset:pick-import",
  ASSET_GET_INFO: "asset:get-info",
  ASSET_READ_TEXT: "asset:read-text",
  ASSET_OPEN_EXTERNAL: "asset:open-external",
  ASSET_MOVE: "asset:move",
  /** Reveal `assets/<relativePath>` in the OS file manager (file → show in folder). */
  ASSET_REVEAL_IN_FILE_MANAGER: "asset:reveal-in-file-manager",
  /** Unified undo (notes snapshot or last asset move), LIFO. */
  NODEX_UNDO: "nodex:undo",
  NODEX_REDO: "nodex:redo",
  /** App-wide preferences (userData JSON, not per-project). */
  APP_GET_PREFS: "app:get-prefs",
  APP_SET_SEED_SAMPLE_NOTES: "app:set-seed-sample-notes",
  /** Shell layout preferences (saved in project prefs). */
  SHELL_GET_LAYOUT: "shell:get-layout",
  SHELL_SET_LAYOUT: "shell:set-layout",
  WPN_LIST_WORKSPACES: "wpn:list-workspaces",
  WPN_CREATE_WORKSPACE: "wpn:create-workspace",
  WPN_UPDATE_WORKSPACE: "wpn:update-workspace",
  WPN_DELETE_WORKSPACE: "wpn:delete-workspace",
  WPN_LIST_PROJECTS: "wpn:list-projects",
  WPN_CREATE_PROJECT: "wpn:create-project",
  WPN_UPDATE_PROJECT: "wpn:update-project",
  WPN_DELETE_PROJECT: "wpn:delete-project",
  WPN_LIST_NOTES: "wpn:list-notes",
  WPN_LIST_ALL_NOTES_WITH_CONTEXT: "wpn:list-all-notes-with-context",
  WPN_LIST_BACKLINKS_TO_NOTE: "wpn:list-backlinks-to-note",
  WPN_GET_NOTE: "wpn:get-note",
  WPN_GET_EXPLORER_STATE: "wpn:get-explorer-state",
  WPN_SET_EXPLORER_STATE: "wpn:set-explorer-state",
  WPN_CREATE_NOTE_IN_PROJECT: "wpn:create-note-in-project",
  WPN_PATCH_NOTE: "wpn:patch-note",
  WPN_DELETE_NOTES: "wpn:delete-notes",
  WPN_MOVE_NOTE: "wpn:move-note",
  WPN_DUPLICATE_NOTE_SUBTREE: "wpn:duplicate-note-subtree",
  /** Main → renderer: periodic nudge to run HTTP sync (`DesktopHost.onSyncTrigger`). */
  DESKTOP_SYNC_TRIGGER: "desktop:sync-trigger",
} as const;

export type IPCChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
